//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Insc_Evento = new HashSet<Insc_Evento>();
        }
    
        public int PK_EVENT { get; set; }
        public string NAME { get; set; }
        public string LOCATION { get; set; }
        public System.DateTime DATE { get; set; }
        public string TYPE { get; set; }
        public string START_TIME { get; set; }
        public string DESCRIPTION { get; set; }
        public int FK_PALESTRANTE { get; set; }
        public int NSLOTS { get; set; }
        public string END_TIME { get; set; }
        public string HOUR { get; set; }
    
        public virtual Palestrante Palestrante { get; set; }
        public virtual ICollection<Insc_Evento> Insc_Evento { get; set; }
    }
}
