//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insc_Evento
    {
        public int PK_INSC_EVENTO { get; set; }
        public int FK_EVENTO { get; set; }
        public int FK_INSCRICAO { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Inscricao Inscricao { get; set; }
    }
}
