//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palestrante
    {
        public Palestrante()
        {
            this.Evento = new HashSet<Evento>();
        }
    
        public int PK_PALESTRANTE { get; set; }
        public string NAME { get; set; }
        public string TITRATION { get; set; }
        public string CV { get; set; }
        public string CITY { get; set; }
        public string TEL { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
