//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        public Participante()
        {
            this.Inscricao = new HashSet<Inscricao>();
        }
    
        public string PK_PARTICIPANTE { get; set; }
        public string NAME { get; set; }
        public string COURSE { get; set; }
        public int PERIOD { get; set; }
        public string TEL { get; set; }
        public string EMAIL { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string PROFILE { get; set; }
    
        public virtual ICollection<Inscricao> Inscricao { get; set; }
    }
}
