//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SemanaTecnologiaEntities : DbContext
    {
        public SemanaTecnologiaEntities()
            : base("name=SemanaTecnologiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Insc_Evento> Insc_Evento { get; set; }
        public DbSet<Inscricao> Inscricao { get; set; }
        public DbSet<Palestrante> Palestrante { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Participante> Participante { get; set; }
    }
}
